/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedDeliveriesDeliveryIdRouteImport } from './routes/_authenticated/deliveries.$deliveryId'
import { Route as AuthenticatedTravelPathsIndexRouteImport } from './routes/_authenticated/travel-paths/index'
import { Route as AuthenticatedTravelPathsRunIdRouteImport } from './routes/_authenticated/travel-paths/$runId'
import { Route as AuthenticatedTravelPathsManageRouteImport } from './routes/_authenticated/travel-paths/manage'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveriesDeliveryIdRoute =
  AuthenticatedDeliveriesDeliveryIdRouteImport.update({
    id: '/deliveries/$deliveryId',
    path: '/deliveries/$deliveryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelPathsIndexRoute =
  AuthenticatedTravelPathsIndexRouteImport.update({
    id: '/travel-paths/',
    path: '/travel-paths/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelPathsRunIdRoute =
  AuthenticatedTravelPathsRunIdRouteImport.update({
    id: '/travel-paths/$runId',
    path: '/travel-paths/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelPathsManageRoute =
  AuthenticatedTravelPathsManageRouteImport.update({
    id: '/travel-paths/manage',
    path: '/travel-paths/manage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/add': typeof AuthenticatedAddRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/search': typeof AuthenticatedSearchRoute
  '/deliveries/$deliveryId': typeof AuthenticatedDeliveriesDeliveryIdRoute
  '/travel-paths/$runId': typeof AuthenticatedTravelPathsRunIdRoute
  '/travel-paths/manage': typeof AuthenticatedTravelPathsManageRoute
  '/travel-paths/': typeof AuthenticatedTravelPathsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/add': typeof AuthenticatedAddRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/search': typeof AuthenticatedSearchRoute
  '/': typeof AuthenticatedIndexRoute
  '/deliveries/$deliveryId': typeof AuthenticatedDeliveriesDeliveryIdRoute
  '/travel-paths/$runId': typeof AuthenticatedTravelPathsRunIdRoute
  '/travel-paths/manage': typeof AuthenticatedTravelPathsManageRoute
  '/travel-paths': typeof AuthenticatedTravelPathsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/deliveries/$deliveryId': typeof AuthenticatedDeliveriesDeliveryIdRoute
  '/_authenticated/travel-paths/$runId': typeof AuthenticatedTravelPathsRunIdRoute
  '/_authenticated/travel-paths/manage': typeof AuthenticatedTravelPathsManageRoute
  '/_authenticated/travel-paths/': typeof AuthenticatedTravelPathsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/add'
    | '/admin'
    | '/search'
    | '/deliveries/$deliveryId'
    | '/travel-paths/$runId'
    | '/travel-paths/manage'
    | '/travel-paths/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/account'
    | '/add'
    | '/admin'
    | '/search'
    | '/'
    | '/deliveries/$deliveryId'
    | '/travel-paths/$runId'
    | '/travel-paths/manage'
    | '/travel-paths'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/add'
    | '/_authenticated/admin'
    | '/_authenticated/search'
    | '/_authenticated/'
    | '/_authenticated/deliveries/$deliveryId'
    | '/_authenticated/travel-paths/$runId'
    | '/_authenticated/travel-paths/manage'
    | '/_authenticated/travel-paths/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries/$deliveryId': {
      id: '/_authenticated/deliveries/$deliveryId'
      path: '/deliveries/$deliveryId'
      fullPath: '/deliveries/$deliveryId'
      preLoaderRoute: typeof AuthenticatedDeliveriesDeliveryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travel-paths/': {
      id: '/_authenticated/travel-paths/'
      path: '/travel-paths'
      fullPath: '/travel-paths/'
      preLoaderRoute: typeof AuthenticatedTravelPathsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travel-paths/$runId': {
      id: '/_authenticated/travel-paths/$runId'
      path: '/travel-paths/$runId'
      fullPath: '/travel-paths/$runId'
      preLoaderRoute: typeof AuthenticatedTravelPathsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travel-paths/manage': {
      id: '/_authenticated/travel-paths/manage'
      path: '/travel-paths/manage'
      fullPath: '/travel-paths/manage'
      preLoaderRoute: typeof AuthenticatedTravelPathsManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDeliveriesDeliveryIdRoute: typeof AuthenticatedDeliveriesDeliveryIdRoute
  AuthenticatedTravelPathsRunIdRoute: typeof AuthenticatedTravelPathsRunIdRoute
  AuthenticatedTravelPathsManageRoute: typeof AuthenticatedTravelPathsManageRoute
  AuthenticatedTravelPathsIndexRoute: typeof AuthenticatedTravelPathsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDeliveriesDeliveryIdRoute:
    AuthenticatedDeliveriesDeliveryIdRoute,
  AuthenticatedTravelPathsRunIdRoute: AuthenticatedTravelPathsRunIdRoute,
  AuthenticatedTravelPathsManageRoute: AuthenticatedTravelPathsManageRoute,
  AuthenticatedTravelPathsIndexRoute: AuthenticatedTravelPathsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
